const prisma = require("../config/prisma");
const service = require("../services/contactService");
const { text, email, phone, cuid, pagination } = require("../utils/validation");
const activityService = require("../services/adminActivityService");

const create = async (req, res, next) => { try { const body = req.body || {}; const data = await prisma.contactMessage.create({ data: { name: text(body.name, "Name", { max: 120 }), email: email(body.email), phone: phone(body.phone, false), subject: text(body.subject, "Subject", { required: false, max: 200 }), message: text(body.message, "Message", { max: 5000 }) } }); await activityService.recordActivity({ type: "CONTACT_MESSAGE_CREATED", title: "New contact message", description: `${data.subject || "A contact message"} was sent by ${data.name}.`, entityType: "contact-message", entityId: data.id }); res.status(201).json({ success: true, data }); } catch (error) { next(error); } };
const list = async (req, res, next) => { try { const { page, pageSize, skip } = pagination(req.query); const data = await service.listMessages({ page, pageSize, skip, search: req.query.search?.trim(), status: req.query.status }); res.json({ success: true, ...data }); } catch (error) { next(error); } };
const get = async (req, res, next) => { try { const data = await prisma.contactMessage.findUnique({ where: { id: cuid(req.params.id) } }); if (!data) return res.status(404).json({ success: false, message: "Contact message not found" }); res.json({ success: true, data }); } catch (error) { next(error); } };
const update = async (req, res, next) => { try { const data = {}; if (req.body.status !== undefined) data.status = req.body.status; if (req.body.adminNotes !== undefined) data.adminNotes = req.body.adminNotes ? text(req.body.adminNotes, "Admin notes", { required: false, max: 5000 }) : null; const result = await prisma.contactMessage.update({ where: { id: cuid(req.params.id) }, data }); res.json({ success: true, data: result }); } catch (error) { next(error); } };
const remove = async (req, res, next) => { try { const id = cuid(req.params.id); await prisma.contactMessage.delete({ where: { id } }); await activityService.recordActivity({ type: "CONTACT_MESSAGE_DELETED", title: "Contact message deleted", description: `Contact message ${id} was deleted.`, entityType: "contact-message", entityId: id, adminId: req.admin.id }); res.json({ success: true, message: "Contact message deleted" }); } catch (error) { next(error); } };
module.exports = { create, list, get, update, remove };