const express = require("express");
const { protect, requireRole } = require("../middleware/authMiddleware");
const products = require("../controllers/productsController");
const customizations = require("../controllers/customizationsController");
const orders = require("../controllers/ordersController");
const requests = require("../controllers/customizationRequestsController");
const contact = require("../controllers/contactController");
const dashboard = require("../controllers/dashboardController");

const router = express.Router();
router.use(protect);
router.get("/dashboard", dashboard.getDashboard);
router.get("/products", products.getAdminProducts);
router.get("/products/:id", products.getProductById);
router.post("/products", products.createProduct);
router.put("/products/:id", products.updateProduct);
router.delete("/products/:id", requireRole("SUPER_ADMIN"), products.deleteProduct);
router.get("/customizations", customizations.getCustomizations);
router.post("/customizations", customizations.createCustomization);
router.put("/customizations/:id", customizations.updateCustomization);
router.delete("/customizations/:id", customizations.deleteCustomization);
router.get("/orders", orders.getOrders);
router.get("/orders/:id", orders.getOrder);
router.patch("/orders/:id/status", orders.updateOrderStatus);
router.patch("/orders/:id/payment", orders.updatePaymentStatus);
router.get("/customization-requests", requests.list);
router.get("/customization-requests/:id", requests.get);
router.patch("/customization-requests/:id/status", requests.update);
router.patch("/customization-requests/:id", requests.update);
router.delete("/customization-requests/:id", requests.remove);
router.get("/contact-messages", contact.list);
router.get("/contact-messages/:id", contact.get);
router.patch("/contact-messages/:id", contact.update);
router.delete("/contact-messages/:id", contact.remove);
module.exports = router;