const React = require("react");
const { Body, Container, Head, Heading, Hr, Html, Img, Preview, Section, Text } = require("@react-email/components");

const h = React.createElement;
const colors = { ink: "#171717", muted: "#737373", border: "#e5e5e5", soft: "#f5f5f5", white: "#ffffff" };
const formatDate = (date) => new Intl.DateTimeFormat("en-GH", { dateStyle: "long", timeZone: "Africa/Accra" }).format(new Date(date));
const labelStyle = { color: colors.muted, fontSize: "12px", letterSpacing: "1.5px", lineHeight: "20px", margin: "0", textTransform: "uppercase" };
const valueStyle = { color: colors.ink, fontSize: "15px", lineHeight: "22px", margin: "4px 0 0", whiteSpace: "pre-wrap" };
const detail = (label, value) => h(Section, { style: { padding: "0 0 16px" } }, h(Text, { style: labelStyle }, label), h(Text, { style: valueStyle }, value));

function AdminCustomizationRequestNotificationEmail({ request }) {
  const logoUrl = process.env.PREPD_EMAIL_LOGO_URL;
  return h(Html, null, h(Head), h(Preview, null, `New PREP'D customization request ${request.reference}`), h(Body, { style: { backgroundColor: colors.soft, fontFamily: "Arial, sans-serif", margin: "0", padding: "32px 16px" } }, h(Container, { style: { backgroundColor: colors.white, margin: "0 auto", maxWidth: "620px", padding: "0 32px" } }, h(Section, { style: { padding: "32px 0 26px" } }, logoUrl ? h(Img, { src: logoUrl, alt: "PREP'D", width: "120", style: { display: "block" } }) : h(Text, { style: { color: colors.ink, fontSize: "24px", fontWeight: "800", margin: "0" } }, "PREP'D")), h(Hr, { style: { borderColor: colors.border, margin: "0" } }), h(Section, { style: { padding: "38px 0 20px" } }, h(Text, { style: { color: colors.muted, fontSize: "13px", letterSpacing: "2px", margin: "0 0 14px", textTransform: "uppercase" } }, "New customization request"), h(Heading, { as: "h1", style: { color: colors.ink, fontSize: "30px", lineHeight: "38px", margin: "0 0 14px" } }, `A new request is ready, ${request.customerName}.`), h(Text, { style: { color: colors.muted, fontSize: "16px", lineHeight: "26px", margin: "0" } }, "A customer has submitted a new PREP'D customization request for review.")), h(Section, { style: { backgroundColor: colors.soft, padding: "20px 22px" } }, detail("Request reference", request.reference), detail("Customer name", request.customerName), detail("Customer email", request.customerEmail), detail("Customer phone", request.customerPhone || "Not provided"), detail("Submission date", formatDate(request.createdAt)), detail("Current status", String(request.status || "PENDING").replace(/_/g, " ")), request.product?.name && detail("Product", request.product.name), request.budget != null && detail("Budget", `GH₵ ${Number(request.budget).toFixed(2)}`), detail("Customization details", request.request)), h(Hr, { style: { borderColor: colors.border, margin: "30px 0 0" } }), h(Section, { style: { padding: "26px 0 34px" } }, h(Text, { style: { color: colors.muted, fontSize: "13px", lineHeight: "21px", margin: "0" } }, "Please review the request in the PREP'D admin dashboard.")))));
}

module.exports = AdminCustomizationRequestNotificationEmail;