const React = require("react");
const { Body, Container, Head, Heading, Hr, Html, Img, Preview, Section, Text } = require("@react-email/components");

const h = React.createElement;
const colors = { ink: "#171717", muted: "#737373", border: "#e5e5e5", soft: "#f5f5f5", white: "#ffffff" };
const formatDate = (date) => new Intl.DateTimeFormat("en-GH", { dateStyle: "long", timeZone: "Africa/Accra" }).format(new Date(date));
const detail = (label, value) => h(Section, { style: { padding: "0 0 18px" } }, h(Text, { style: { color: colors.muted, fontSize: "12px", letterSpacing: "1.5px", lineHeight: "20px", margin: "0", textTransform: "uppercase" } }, label), h(Text, { style: { color: colors.ink, fontSize: "15px", lineHeight: "22px", margin: "4px 0 0", whiteSpace: "pre-wrap" } }, value));

function CustomizationRequestConfirmationEmail({ request }) {
  const logoUrl = process.env.PREPD_EMAIL_LOGO_URL;
  return h(Html, null, h(Head), h(Preview, null, `Your PREP'D customization request ${request.reference} has been received`), h(Body, { style: { backgroundColor: colors.soft, fontFamily: "Arial, sans-serif", margin: "0", padding: "32px 16px" } }, h(Container, { style: { backgroundColor: colors.white, margin: "0 auto", maxWidth: "620px", padding: "0 32px" } }, h(Section, { style: { padding: "32px 0 26px" } }, logoUrl ? h(Img, { src: logoUrl, alt: "PREP'D", width: "120", style: { display: "block" } }) : h(Text, { style: { color: colors.ink, fontSize: "24px", fontWeight: "800", margin: "0" } }, "PREP'D")), h(Hr, { style: { borderColor: colors.border, margin: "0" } }), h(Section, { style: { padding: "38px 0 20px" } }, h(Text, { style: { color: colors.muted, fontSize: "13px", letterSpacing: "2px", margin: "0 0 14px", textTransform: "uppercase" } }, "Customization request received"), h(Heading, { as: "h1", style: { color: colors.ink, fontSize: "30px", lineHeight: "38px", margin: "0 0 14px" } }, `We've got you, ${request.customerName}.`), h(Text, { style: { color: colors.muted, fontSize: "16px", lineHeight: "26px", margin: "0" } }, "Thanks for reaching out. PREP'D has received your customization request and our team will review it carefully.")), h(Section, { style: { backgroundColor: colors.soft, padding: "20px 22px" } }, detail("Request ID", request.reference), detail("Submitted", formatDate(request.createdAt)), detail("Current status", String(request.status || "PENDING").replace(/_/g, " ")), request.product?.name && detail("Product", request.product.name), detail("Requested customization", request.request)), h(Hr, { style: { borderColor: colors.border, margin: "30px 0 0" } }), h(Section, { style: { padding: "26px 0 34px" } }, h(Text, { style: { color: colors.muted, fontSize: "13px", lineHeight: "21px", margin: "0" } }, "We will contact you with the next step. Thank you for trusting PREP'D to make it personal."), h(Text, { style: { color: colors.muted, fontSize: "12px", lineHeight: "20px", margin: "16px 0 0" } }, "PREP'D - thoughtfully prepared for your next step.")))));
}

module.exports = CustomizationRequestConfirmationEmail;