const React = require("react");
const { Body, Container, Head, Heading, Hr, Html, Img, Preview, Section, Text } = require("@react-email/components");

const h = React.createElement;
const colors = { ink: "#171717", muted: "#737373", border: "#e5e5e5", soft: "#f5f5f5", white: "#ffffff" };
const formatDate = (date) => new Intl.DateTimeFormat("en-GH", { dateStyle: "long", timeZone: "Africa/Accra" }).format(new Date(date));

function CustomizationCompletionEmail({ request }) {
  const logoUrl = process.env.PREPD_EMAIL_LOGO_URL;
  return h(Html, null, h(Head), h(Preview, null, `Your PREP'D customization request ${request.reference} is complete`), h(Body, { style: { backgroundColor: colors.soft, fontFamily: "Arial, sans-serif", margin: "0", padding: "32px 16px" } }, h(Container, { style: { backgroundColor: colors.white, margin: "0 auto", maxWidth: "620px", padding: "0 32px" } }, h(Section, { style: { padding: "32px 0 26px" } }, logoUrl ? h(Img, { src: logoUrl, alt: "PREP'D", width: "120", style: { display: "block" } }) : h(Text, { style: { color: colors.ink, fontSize: "24px", fontWeight: "800", margin: "0" } }, "PREP'D")), h(Hr, { style: { borderColor: colors.border, margin: "0" } }), h(Section, { style: { padding: "38px 0 20px" } }, h(Text, { style: { color: colors.muted, fontSize: "13px", letterSpacing: "2px", margin: "0 0 14px", textTransform: "uppercase" } }, "Customization complete"), h(Heading, { as: "h1", style: { color: colors.ink, fontSize: "30px", lineHeight: "38px", margin: "0 0 14px" } }, `It's ready, ${request.customerName}.`), h(Text, { style: { color: colors.muted, fontSize: "16px", lineHeight: "26px", margin: "0" } }, "Your PREP'D customization request has been completed. Our team is ready to share the next step with you.")), h(Section, { style: { backgroundColor: colors.soft, padding: "20px 22px" } }, h(Text, { style: { color: colors.muted, fontSize: "12px", margin: "0 0 4px", textTransform: "uppercase" } }, "Request ID"), h(Text, { style: { color: colors.ink, fontSize: "15px", margin: "0 0 18px" } }, request.reference), h(Text, { style: { color: colors.muted, fontSize: "12px", margin: "0 0 4px", textTransform: "uppercase" } }, "Completion date"), h(Text, { style: { color: colors.ink, fontSize: "15px", margin: "0 0 18px" } }, formatDate(request.updatedAt || new Date())), h(Text, { style: { color: colors.muted, fontSize: "12px", margin: "0 0 4px", textTransform: "uppercase" } }, "Requested customization"), h(Text, { style: { color: colors.ink, fontSize: "15px", lineHeight: "22px", margin: "0", whiteSpace: "pre-wrap" } }, request.request)), h(Hr, { style: { borderColor: colors.border, margin: "30px 0 0" } }), h(Section, { style: { padding: "26px 0 34px" } }, h(Text, { style: { color: colors.muted, fontSize: "13px", lineHeight: "21px", margin: "0" } }, "Thank you for trusting PREP'D with your idea. We look forward to helping you make it yours.")))));
}

module.exports = CustomizationCompletionEmail;