const React = require("react");
const { Body, Container, Head, Heading, Hr, Html, Img, Preview, Row, Section, Text } = require("@react-email/components");

const h = React.createElement;
const colors = { ink: "#171717", muted: "#737373", border: "#e5e5e5", soft: "#f5f5f5", white: "#ffffff" };
const formatDate = (date) => new Intl.DateTimeFormat("en-GH", { dateStyle: "long", timeZone: "Africa/Accra" }).format(new Date(date));
const money = (value, currency = "GH₵") => `${currency} ${Number(value || 0).toFixed(2)}`;

function OrderCompletionEmail({ order }) {
  const logoUrl = process.env.PREPD_EMAIL_LOGO_URL;
  return h(Html, null, h(Head), h(Preview, null, `Your PREP'D order ${order.reference} is complete`), h(Body, { style: { backgroundColor: colors.soft, fontFamily: "Arial, sans-serif", margin: "0", padding: "32px 16px" } }, h(Container, { style: { backgroundColor: colors.white, margin: "0 auto", maxWidth: "620px", padding: "0 32px" } }, h(Section, { style: { padding: "32px 0 26px" } }, logoUrl ? h(Img, { src: logoUrl, alt: "PREP'D", width: "120", style: { display: "block" } }) : h(Text, { style: { color: colors.ink, fontSize: "24px", fontWeight: "800", margin: "0" } }, "PREP'D")), h(Hr, { style: { borderColor: colors.border, margin: "0" } }), h(Section, { style: { padding: "38px 0 20px" } }, h(Text, { style: { color: colors.muted, fontSize: "13px", letterSpacing: "2px", margin: "0 0 14px", textTransform: "uppercase" } }, "Order complete"), h(Heading, { as: "h1", style: { color: colors.ink, fontSize: "30px", lineHeight: "38px", margin: "0 0 14px" } }, `Your order is ready, ${order.customerName}.`), h(Text, { style: { color: colors.muted, fontSize: "16px", lineHeight: "26px", margin: "0" } }, "Your PREP'D order has been completed. We hope it makes your next step a little easier.")), h(Section, { style: { backgroundColor: colors.soft, padding: "20px 22px" } }, h(Row, null, h(Text, { style: { color: colors.muted, fontSize: "12px", margin: "0 0 4px", textTransform: "uppercase" } }, "Order number"), h(Text, { style: { color: colors.ink, fontSize: "15px", margin: "0 0 18px" } }, order.reference)), h(Row, null, h(Text, { style: { color: colors.muted, fontSize: "12px", margin: "0 0 4px", textTransform: "uppercase" } }, "Completion date"), h(Text, { style: { color: colors.ink, fontSize: "15px", margin: "0" } }, formatDate(order.updatedAt || new Date())))), h(Heading, { as: "h2", style: { color: colors.ink, fontSize: "20px", margin: "34px 0 16px" } }, "Your order"), ...(order.items || []).map((item) => h(Row, { key: item.id, style: { borderBottom: `1px solid ${colors.border}` } }, h(Text, { style: { color: colors.ink, fontSize: "15px", margin: "14px 0" } }, `${item.productName} x ${item.quantity}`), h(Text, { style: { color: colors.ink, fontSize: "15px", margin: "14px 0", textAlign: "right" } }, money(item.totalPrice, order.currency))), h(Hr, { style: { borderColor: colors.border, margin: "20px 0 0" } }), h(Row, null, h(Text, { style: { color: colors.ink, fontSize: "17px", fontWeight: "700", margin: "16px 0 28px" } }, "Total"), h(Text, { style: { color: colors.ink, fontSize: "17px", fontWeight: "700", margin: "16px 0 28px", textAlign: "right" } }, money(order.total, order.currency))), h(Hr, { style: { borderColor: colors.border, margin: "0" } }), h(Section, { style: { padding: "26px 0 34px" } }, h(Text, { style: { color: colors.muted, fontSize: "13px", lineHeight: "21px", margin: "0" } }, "Thank you for choosing PREP'D. We appreciate your order and hope you enjoy every detail."))))));
}

module.exports = OrderCompletionEmail;